services:
  main:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - USER=$USER
        - UID=$UID
        - GID=$GID
        - USER_PASSWD=$USER_PASSWD
        - ROOT_PASSWD=$ROOT_PASSWD
        - PYTHON_VERSION=$PYTHON_VERSION
        - SSH_PORT=$SSH_PORT
        - Jupyter_PORT=$Jupyter_PORT
    command: sudo service ssh start && bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - $PWD/work:/home/$USER/work
    ports:
      - $HOST_PORT:$CONTAINER_PORT
      - $Jupyter_PORT:$Jupyter_PORT
    tty: true